In [2]:
import torch

In [3]:
torch.empty(5, 3)

tensor([[ 0.0000e+00,  2.0000e+00, -6.2170e+32],
        [ 1.5849e+29,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
torch.rand(5, 3)

tensor([[0.0290, 0.7536, 0.4018],
        [0.3132, 0.0028, 0.6553],
        [0.4663, 0.0589, 0.5638],
        [0.0405, 0.0353, 0.9120],
        [0.7697, 0.8639, 0.8471]])

In [13]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [14]:
x = torch.tensor([3.3, 5])
x

tensor([3.3000, 5.0000])

In [15]:
x = x.new_ones(5, 3, dtype=torch.double)

In [16]:
torch.randn_like(x, dtype=torch.float)

tensor([[ 1.0136, -0.9861, -0.7379],
        [-0.6395, -0.2944,  1.5987],
        [-0.0534, -0.3049, -0.2917],
        [ 2.4367, -0.3919,  1.9873],
        [ 0.8687, -0.7861, -1.0693]])

In [17]:
y = torch.rand(5, 3)

In [18]:
x + y

tensor([[1.3015, 1.5363, 1.4194],
        [1.8083, 1.6153, 1.2227],
        [1.5909, 1.3526, 1.5095],
        [1.7160, 1.3498, 1.1375],
        [1.5191, 1.6559, 1.2612]], dtype=torch.float64)

In [21]:
x = torch.randn(4, 4)
y = x.view(16)
y

tensor([ 0.2453,  0.5872,  1.0513, -0.2208, -1.0339, -0.0752,  0.3489,  0.8131,
         0.8910,  0.7885, -0.5863,  1.5158, -0.3403,  0.4298, -0.2045,  1.6901])

In [51]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [52]:
y = x + 1
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [26]:
y.grad_fn

In [53]:
z = y ** 3
z

tensor([[8., 8.],
        [8., 8.]], grad_fn=<PowBackward0>)

In [35]:
x.requires_grad_(False)

tensor([[1., 1.],
        [1., 1.]])

In [37]:
y.requires_grad

True

In [57]:
out = z.mean()
out

tensor(8., grad_fn=<MeanBackward0>)

In [58]:
out.backward()
x.grad

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.